### ISSUE TITLE
运行支付宝端 报错：@tarojs/components' does not contain an export named 'OpenData'.

### ISSUE THREAD

**Issue by MonthPearl** [b2nil/taro-ui-vue3-demo#2]
问题描述：
npm install 后
运行yarn dev:alipay 
报下面错误
./node_modules/taro-ui-vue3/dist/index.esm.js 993:92-100
" '@tarojs/components' does not contain an export named 'OpenData'.

**Comment by zjy2931** [comment]
同样的错误

**Comment by b2nil** [comment]
https://github.com/b2nil/taro-ui-vue3/issues/103
