### ISSUE TITLE
克隆项目之后安装，使用 npm run:weapp  运行发现找不到依赖插件

### ISSUE THREAD

**Issue by kokodayou2000** [b2nil/taro-ui-vue3-demo#5]
👽 Taro v3.6.8

找不到插件依赖 "@tarojs/plugin-platform-weapp"，请先在项目中安装，项目路径：C:\Users\03062\taro-weixinapp\taro-ui-vue3-demo

**Comment by b2nil** [comment]
由于很久没有更新，这个 Demo 的配置已经严重过时了。请自行根据 Taro 最新文档配置一下`package.json`中的依赖项，以及 `config` 中的一些开发配置。
